[PARSER]
    Name docker_json
    Format json
    Time_Key time
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z

[PARSER]
    Name rails_log
    Format regex
    Regex ^(?<level>[IWEF]), \[(?<timestamp>[^\]]+) #(?<pid>\d+)\]\s+(?<severity>\w+)\s+--\s+:\s+(?<message>.*)$
    Time_Key timestamp
    Time_Format %Y-%m-%dT%H:%M:%S.%L

[PARSER]
    Name rails_json_log
    Format regex
    Regex ^(?<level>[IWEF]), \[(?<timestamp>[^\]]+) #(?<pid>\d+)\]\s+(?<severity>\w+)\s+--\s+:\s+(?<json_message>\{.+\})$
    Time_Key timestamp
    Time_Format %Y-%m-%dT%H:%M:%S.%L

[PARSER]
    Name json_fields
    Format json