/* eslint-disable */
// Generated by scripts/cloudflare-types.mjs. Target values are intentionally widened.
interface __BaseEnv_Env {
	ANALYTICS: AnalyticsEngineDataset;
	ENVIRONMENT: string;
	ANALYTICS_DATASET: string;
	CLOUDFLARE_ANALYTICS_ACCOUNT_ID: string;
	CLOUDFLARE_ANALYTICS_TOKEN: string;
	OBSERVABILITY_INTERNAL_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "ANALYTICS_DATASET" | "CLOUDFLARE_ANALYTICS_ACCOUNT_ID" | "CLOUDFLARE_ANALYTICS_TOKEN" | "OBSERVABILITY_INTERNAL_TOKEN">> {}
}

// Secret bindings are generated from the declarative service or target registry.
declare namespace Cloudflare {
	interface Env {
	OBSERVABILITY_INTERNAL_TOKEN: string;
	OBSERVABILITY_INTERNAL_TOKEN_PREVIOUS?: string;
	CLOUDFLARE_ANALYTICS_ACCOUNT_ID: string;
	CLOUDFLARE_ANALYTICS_TOKEN: string;
	}
}
interface Env {
	OBSERVABILITY_INTERNAL_TOKEN: string;
	OBSERVABILITY_INTERNAL_TOKEN_PREVIOUS?: string;
	CLOUDFLARE_ANALYTICS_ACCOUNT_ID: string;
	CLOUDFLARE_ANALYTICS_TOKEN: string;
}
