version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      compatible-updates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
    groups:
      compatible-updates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
