/* eslint-disable */
// Generated by scripts/cloudflare-types.mjs. Target values are intentionally widened.
interface __BaseEnv_Env {
	ARCHIVE: R2Bucket;
	DB: D1Database;
	FLOW_EVENTS: Queue;
	ENVIRONMENT: string;
	SERVICE_NAME: string;
	D1_EXPECTED_MIGRATION: string;
	AUTH_GATEWAY_ISSUER: string;
	AUTH_GATEWAY_AUDIENCE: string;
	AUTH_GATEWAY_JWKS_URL: string;
	PUBLIC_API_URL: string;
	QUEUE_NAME: string;
	DLQ_NAME: string;
	FLOW_USER_ENCRYPTION_KEY: string;
	FLOW_USER_HASH_KEY: string;
	INTERNAL_API_TOKEN: string;
	FLOW_USER_RUNTIME: DurableObjectNamespace<import("./src/index").FlowUserRuntime>;
	FLOW_REALTIME_HUB: DurableObjectNamespace<import("./src/index").FlowRealtimeHub>;
	PRODUCTS_MODULE: Fetcher;
	FLOW_DELAY_EXECUTION: Workflow<Parameters<import("./src/index").FlowDelayExecution['run']>[0]['payload']>;
	FLOW_MAINTENANCE_EXECUTION: Workflow<Parameters<import("./src/index").FlowMaintenanceExecution['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "FlowUserRuntime" | "FlowRealtimeHub";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "SERVICE_NAME" | "D1_EXPECTED_MIGRATION" | "AUTH_GATEWAY_ISSUER" | "AUTH_GATEWAY_AUDIENCE" | "AUTH_GATEWAY_JWKS_URL" | "PUBLIC_API_URL" | "QUEUE_NAME" | "DLQ_NAME" | "FLOW_USER_ENCRYPTION_KEY" | "FLOW_USER_HASH_KEY" | "INTERNAL_API_TOKEN">> {}
}

// Secret bindings are generated from the declarative service or target registry.
declare namespace Cloudflare {
	interface Env {
	INTERNAL_API_TOKEN: string;
	INTERNAL_API_TOKEN_PREVIOUS?: string;
	FLOW_USER_ENCRYPTION_KEY: string;
	FLOW_USER_ENCRYPTION_KEY_PREVIOUS?: string;
	FLOW_USER_HASH_KEY: string;
	}
}
interface Env {
	INTERNAL_API_TOKEN: string;
	INTERNAL_API_TOKEN_PREVIOUS?: string;
	FLOW_USER_ENCRYPTION_KEY: string;
	FLOW_USER_ENCRYPTION_KEY_PREVIOUS?: string;
	FLOW_USER_HASH_KEY: string;
}
