FROM ruby:3.3.8

# Install dependencies
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

# Set working directory
WORKDIR /app

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy the application
COPY ./ ./

ENV RAILS_ENV=production

# Precompile assets
RUN SECRET_KEY_BASE=$(bundle exec rails secret) bundle exec rails assets:precompile

# Start the server
EXPOSE 3000
CMD ["bundle", "exec", "puma", "-b", "tcp://0.0.0.0:3000"]