name: superboard_reference
description: Executable Flutter and FlutterFlow reference application for SuperBoard.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=3.38.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  http: ">=1.2.0 <2.0.0"
  superboard_flutterflow:
    path: ../../sdks/flutterflow
  url_launcher: ">=6.3.1 <7.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  superboard_flutter:
    path: ../../sdks/flutter

flutter:
  uses-material-design: true
