/* eslint-disable */
// Generated by scripts/cloudflare-types.mjs. Target values are intentionally widened.
interface __BaseEnv_Env {
	DB: D1Database;
	ENVIRONMENT: string;
	SERVICE_NAME: string;
	D1_EXPECTED_MIGRATION: string;
	AUTH_GATEWAY_ISSUER: string;
	AUTH_GATEWAY_AUDIENCE: string;
	AUTH_GATEWAY_JWKS_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "SERVICE_NAME" | "D1_EXPECTED_MIGRATION" | "AUTH_GATEWAY_ISSUER" | "AUTH_GATEWAY_AUDIENCE" | "AUTH_GATEWAY_JWKS_URL">> {}
}

// Secret bindings are generated from the declarative service or target registry.
declare namespace Cloudflare {
	interface Env {
	INTERNAL_API_TOKEN: string;
	INTERNAL_API_TOKEN_PREVIOUS?: string;
	}
}
interface Env {
	INTERNAL_API_TOKEN: string;
	INTERNAL_API_TOKEN_PREVIOUS?: string;
}
