// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm } from "emdash";

export interface View {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  plugin_id: string;
  route_id: string;
  path: string;
  description?: string;
  renderer_id: string;
  presentation: unknown;
  bindings: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    views: View;
  }
}