/* eslint-disable */
// Generated by scripts/cloudflare-types.mjs. Target values are intentionally widened.
interface __BaseEnv_Env {
	KV: KVNamespace;
	R2: R2Bucket;
	DB: D1Database;
	BILLING_QUEUE: Queue;
	ENVIRONMENT: string;
	API_DOMAIN: string;
	SDK_DOMAIN: string;
	CREDENTIAL_KEY_SCOPE: string;
	BILLING_RELEASE_STALE_MINUTES: string;
	BILLING_CATALOG_STALE_HOURS: string;
	BILLING_QUEUE_NAME: string;
	BILLING_DLQ_NAME: string;
	AUTH_GATEWAY_ISSUER: string;
	AUTH_GATEWAY_AUDIENCE: string;
	AUTH_GATEWAY_JWKS_URL: string;
	APPLE_ROOT_CERTIFICATES_B64: string;
	INTERNAL_API_TOKEN: string;
	OPENGROW_ENTITLEMENT_WEBHOOK_SECRET: string;
	PURCHASES_SIGNING_KEYSET: string;
	STORE_CREDENTIALS_ACTIVE_KEY_VERSION: string;
	STORE_CREDENTIALS_ENCRYPTION_KEYS: string;
	ANALYTICS_MODULE: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "API_DOMAIN" | "SDK_DOMAIN" | "CREDENTIAL_KEY_SCOPE" | "BILLING_RELEASE_STALE_MINUTES" | "BILLING_CATALOG_STALE_HOURS" | "BILLING_QUEUE_NAME" | "BILLING_DLQ_NAME" | "AUTH_GATEWAY_ISSUER" | "AUTH_GATEWAY_AUDIENCE" | "AUTH_GATEWAY_JWKS_URL" | "APPLE_ROOT_CERTIFICATES_B64" | "INTERNAL_API_TOKEN" | "OPENGROW_ENTITLEMENT_WEBHOOK_SECRET" | "PURCHASES_SIGNING_KEYSET" | "STORE_CREDENTIALS_ACTIVE_KEY_VERSION" | "STORE_CREDENTIALS_ENCRYPTION_KEYS">> {}
}

// Secret bindings are generated from the declarative service or target registry.
declare namespace Cloudflare {
	interface Env {
	GOOGLE_PLAY_SERVICE_ACCOUNT_JSON: string;
	STORE_CREDENTIALS_ENCRYPTION_KEY: string;
	STORE_CREDENTIALS_ENCRYPTION_KEYS: string;
	STORE_CREDENTIALS_ACTIVE_KEY_VERSION: string;
	PURCHASES_SIGNING_KEYSET: string;
	OPENGROW_ENTITLEMENT_WEBHOOK_SECRET: string;
	APPLE_ROOT_CERTIFICATES_B64: string;
	INTERNAL_API_TOKEN: string;
	INTERNAL_API_TOKEN_PREVIOUS?: string;
	}
}
interface Env {
	GOOGLE_PLAY_SERVICE_ACCOUNT_JSON: string;
	STORE_CREDENTIALS_ENCRYPTION_KEY: string;
	STORE_CREDENTIALS_ENCRYPTION_KEYS: string;
	STORE_CREDENTIALS_ACTIVE_KEY_VERSION: string;
	PURCHASES_SIGNING_KEYSET: string;
	OPENGROW_ENTITLEMENT_WEBHOOK_SECRET: string;
	APPLE_ROOT_CERTIFICATES_B64: string;
	INTERNAL_API_TOKEN: string;
	INTERNAL_API_TOKEN_PREVIOUS?: string;
}
