/* eslint-disable */
// Generated by scripts/cloudflare-types.mjs. Target values are intentionally widened.
interface __BaseEnv_Env {
	VOCOSTAR_DB: D1Database;
	APP_KEY: string;
	ENVIRONMENT: string;
	CUSTOM_WORKER_CAPABILITIES: string;
	FILES_INPUT_ORIGIN: string;
	D1_EXPECTED_MIGRATION: string;
	MAX_AUTOMATIC_DISPATCH_ATTEMPTS: string;
	CUSTOM_WORKER_TOKEN: string;
	FILES_INTERNAL_TOKEN: string;
	VOCALS_ORCHESTRATOR: Fetcher;
	MEDIAS_ORCHESTRATOR: Fetcher;
	FILES_SERVICE: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_KEY" | "ENVIRONMENT" | "CUSTOM_WORKER_CAPABILITIES" | "FILES_INPUT_ORIGIN" | "D1_EXPECTED_MIGRATION" | "MAX_AUTOMATIC_DISPATCH_ATTEMPTS" | "CUSTOM_WORKER_TOKEN" | "FILES_INTERNAL_TOKEN">> {}
}

// Secret bindings are generated from the declarative service or target registry.
declare namespace Cloudflare {
	interface Env {
	CUSTOM_WORKER_TOKEN: string;
	FILES_INTERNAL_TOKEN: string;
	CUSTOM_WORKER_TOKEN_PREVIOUS?: string;
	}
}
interface Env {
	CUSTOM_WORKER_TOKEN: string;
	FILES_INTERNAL_TOKEN: string;
	CUSTOM_WORKER_TOKEN_PREVIOUS?: string;
}
