type EmailQueueJob = { type: "email.deliver"; messageId: string };
/* eslint-disable */
// Generated by scripts/cloudflare-types.mjs. Target values are intentionally widened.
interface __BaseEnv_Env {
	DB: D1Database;
	EMAIL_QUEUE: Queue<EmailQueueJob>;
	ENVIRONMENT: string;
	D1_EXPECTED_MIGRATION: string;
	MAIL_TRANSPORT: "capture" | "smtp";
	MAIL_PROVIDER: "smtp" | "aws-ses";
	MAIL_FROM_NAME: string;
	MAIL_FROM_ADDRESS: string;
	MAIL_REPLY_TO: string;
	EMAIL_QUEUE_NAME: string;
	EMAIL_DLQ_NAME: string;
	AWS_REGION: string;
	AWS_SES_CONFIGURATION_SET: string;
	AWS_SES_SMTP_PASSWORD: string;
	AWS_SES_SMTP_USERNAME: string;
	AWS_SES_SNS_TOPIC_ARN: string;
	EMAIL_INTERNAL_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "D1_EXPECTED_MIGRATION" | "MAIL_TRANSPORT" | "MAIL_PROVIDER" | "MAIL_FROM_NAME" | "MAIL_FROM_ADDRESS" | "MAIL_REPLY_TO" | "EMAIL_QUEUE_NAME" | "EMAIL_DLQ_NAME" | "AWS_REGION" | "AWS_SES_CONFIGURATION_SET" | "AWS_SES_SMTP_PASSWORD" | "AWS_SES_SMTP_USERNAME" | "AWS_SES_SNS_TOPIC_ARN" | "EMAIL_INTERNAL_TOKEN">> {}
}

// Secret bindings are generated from the declarative service or target registry.
declare namespace Cloudflare {
	interface Env {
	EMAIL_INTERNAL_TOKEN: string;
	EMAIL_INTERNAL_TOKEN_PREVIOUS?: string;
	MAIL_PREVIEW_TOKEN?: string;
	AWS_SES_SMTP_USERNAME?: string;
	AWS_SES_SMTP_PASSWORD?: string;
	AWS_SES_SNS_TOPIC_ARN?: string;
	SMTP_HOST?: string;
	SMTP_PORT?: string;
	SMTP_SECURITY?: "tls" | "starttls" | "plain";
	SMTP_USERNAME?: string;
	SMTP_PASSWORD?: string;
	}
}
interface Env {
	EMAIL_INTERNAL_TOKEN: string;
	EMAIL_INTERNAL_TOKEN_PREVIOUS?: string;
	MAIL_PREVIEW_TOKEN?: string;
	AWS_SES_SMTP_USERNAME?: string;
	AWS_SES_SMTP_PASSWORD?: string;
	AWS_SES_SNS_TOPIC_ARN?: string;
	SMTP_HOST?: string;
	SMTP_PORT?: string;
	SMTP_SECURITY?: "tls" | "starttls" | "plain";
	SMTP_USERNAME?: string;
	SMTP_PASSWORD?: string;
}
