/* eslint-disable */
// Generated by scripts/cloudflare-types.mjs. Target values are intentionally widened.
interface __BaseEnv_Env {
	FILES: R2Bucket;
	DB: D1Database;
	ENVIRONMENT: string;
	D1_EXPECTED_MIGRATION: string;
	AUTH_GATEWAY_ISSUER: string;
	APPLICATION_AUDIENCE: string;
	AUTH_GATEWAY_JWKS_URL: string;
	MAX_FILE_BYTES: string;
	FILES_PUBLIC_ORIGIN: string;
	DOWNLOAD_TICKET_TTL_SECONDS: string;
	ALLOWED_FILE_CONTENT_TYPES_JSON: string;
	FILES_DOWNLOAD_SIGNING_KEY: string;
	FILES_INTERNAL_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "D1_EXPECTED_MIGRATION" | "AUTH_GATEWAY_ISSUER" | "APPLICATION_AUDIENCE" | "AUTH_GATEWAY_JWKS_URL" | "MAX_FILE_BYTES" | "FILES_PUBLIC_ORIGIN" | "DOWNLOAD_TICKET_TTL_SECONDS" | "ALLOWED_FILE_CONTENT_TYPES_JSON" | "FILES_DOWNLOAD_SIGNING_KEY" | "FILES_INTERNAL_TOKEN">> {}
}

// Secret bindings are generated from the declarative service or target registry.
declare namespace Cloudflare {
	interface Env {
	FILES_INTERNAL_TOKEN: string;
	FILES_INTERNAL_TOKEN_PREVIOUS?: string;
	FILES_DOWNLOAD_SIGNING_KEY: string;
	FILES_DOWNLOAD_SIGNING_KEY_PREVIOUS?: string;
	}
}
interface Env {
	FILES_INTERNAL_TOKEN: string;
	FILES_INTERNAL_TOKEN_PREVIOUS?: string;
	FILES_DOWNLOAD_SIGNING_KEY: string;
	FILES_DOWNLOAD_SIGNING_KEY_PREVIOUS?: string;
}
