ALTER TABLE links ADD COLUMN name TEXT NOT NULL DEFAULT '';
ALTER TABLE links ADD COLUMN destinations_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(destinations_json));
ALTER TABLE links ADD COLUMN campaign_id TEXT REFERENCES campaigns(id) ON DELETE SET NULL;
ALTER TABLE links ADD COLUMN title TEXT;
ALTER TABLE links ADD COLUMN subtitle TEXT;
ALTER TABLE links ADD COLUMN image_url TEXT;
ALTER TABLE links ADD COLUMN utm_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(utm_json));
ALTER TABLE links ADD COLUMN updated_at TEXT;
ALTER TABLE campaigns ADD COLUMN slug TEXT;
ALTER TABLE campaigns ADD COLUMN status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','active','archived'));
ALTER TABLE campaigns ADD COLUMN metadata_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata_json));
ALTER TABLE campaigns ADD COLUMN updated_at TEXT;
ALTER TABLE redirect_rules ADD COLUMN name TEXT NOT NULL DEFAULT 'Redirect rule';
ALTER TABLE redirect_rules ADD COLUMN active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1));
ALTER TABLE redirect_rules ADD COLUMN created_at TEXT;
ALTER TABLE redirect_rules ADD COLUMN updated_at TEXT;
ALTER TABLE audit_events ADD COLUMN actor_id TEXT;
ALTER TABLE audit_events ADD COLUMN request_id TEXT;
CREATE UNIQUE INDEX campaigns_project_slug ON campaigns(project_id,slug);
CREATE INDEX links_project_campaign ON links(project_id,campaign_id,created_at DESC);
UPDATE links SET updated_at=COALESCE(created_at,CURRENT_TIMESTAMP);
UPDATE campaigns SET updated_at=COALESCE(created_at,CURRENT_TIMESTAMP);
UPDATE redirect_rules SET created_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE created_at IS NULL OR updated_at IS NULL;

CREATE TABLE domains (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,hostname TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','verified','failed')),verification_token TEXT NOT NULL,verified_at TEXT,is_default INTEGER NOT NULL DEFAULT 0 CHECK(is_default IN (0,1)),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(project_id,hostname));
CREATE TABLE social_previews (project_id TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT,image_url TEXT,site_name TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE tracking_settings (project_id TEXT PRIMARY KEY,enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN (0,1)),provider TEXT NOT NULL DEFAULT 'opengrow',configuration_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(configuration_json)),updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE link_events (id TEXT NOT NULL,project_id TEXT NOT NULL,link_id TEXT,campaign_id TEXT,event_type TEXT NOT NULL CHECK(event_type IN ('click','redirect','install','open','conversion')),platform TEXT,country_code TEXT,occurred_at TEXT NOT NULL,metadata_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata_json)),PRIMARY KEY(project_id,id));
CREATE INDEX link_events_stats ON link_events(project_id,occurred_at,event_type,platform,campaign_id);
CREATE TABLE idempotency_keys (project_id TEXT NOT NULL,key TEXT NOT NULL,response_json TEXT NOT NULL CHECK(json_valid(response_json)),status_code INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(project_id,key));
