/* eslint-disable */
// Generated by scripts/cloudflare-types.mjs. Target values are intentionally widened.
interface __BaseEnv_Env {
	ATTACHMENTS: R2Bucket;
	DB: D1Database;
	SUPPORT_QUEUE: Queue;
	ENVIRONMENT: string;
	SERVICE_NAME: string;
	D1_EXPECTED_MIGRATION: string;
	AUTH_GATEWAY_ISSUER: string;
	AUTH_GATEWAY_AUDIENCE: string;
	AUTH_GATEWAY_JWKS_URL: string;
	CORS_ORIGIN: string;
	ALLOWED_PROJECT_IDS: string;
	QUEUE_NAME: string;
	DLQ_NAME: string;
	INTERNAL_API_TOKEN: string;
	SUPPORT_WEBHOOK_ENCRYPTION_KEY: string;
	CONVERSATIONS: DurableObjectNamespace<import("./src/index").ConversationRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ConversationRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "SERVICE_NAME" | "D1_EXPECTED_MIGRATION" | "AUTH_GATEWAY_ISSUER" | "AUTH_GATEWAY_AUDIENCE" | "AUTH_GATEWAY_JWKS_URL" | "CORS_ORIGIN" | "ALLOWED_PROJECT_IDS" | "QUEUE_NAME" | "DLQ_NAME" | "INTERNAL_API_TOKEN" | "SUPPORT_WEBHOOK_ENCRYPTION_KEY">> {}
}

// Secret bindings are generated from the declarative service or target registry.
declare namespace Cloudflare {
	interface Env {
	INTERNAL_API_TOKEN: string;
	INTERNAL_API_TOKEN_PREVIOUS?: string;
	SUPPORT_WEBHOOK_ENCRYPTION_KEY: string;
	}
}
interface Env {
	INTERNAL_API_TOKEN: string;
	INTERNAL_API_TOKEN_PREVIOUS?: string;
	SUPPORT_WEBHOOK_ENCRYPTION_KEY: string;
}
