/* eslint-disable */
// Generated by scripts/cloudflare-types.mjs. Target values are intentionally widened.
interface __BaseEnv_Env {
	ENVIRONMENT: string;
	OPENGROW_TARGET: string;
	MCP_DOMAIN: string;
	PUBLIC_API_URL: string;
	PUBLIC_MCP_URL: string;
	API_SERVICE: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "OPENGROW_TARGET" | "MCP_DOMAIN" | "PUBLIC_API_URL" | "PUBLIC_MCP_URL">> {}
}

// Secret bindings are generated from the declarative service or target registry.
declare namespace Cloudflare {
	interface Env {

	}
}
interface Env {

}
