/* eslint-disable */
// Generated by scripts/cloudflare-types.mjs. Target values are intentionally widened.
interface __BaseEnv_Env {
	DB: D1Database;
	ENVIRONMENT: string;
	D1_EXPECTED_MIGRATION: string;
	REGISTRATION_MODE: string;
	APPLICATION_AUDIENCE: string;
	OPENGROW_IDENTITY_ISSUER: string;
	OPENGROW_IDENTITY_AUDIENCE: string;
	OPENGROW_IDENTITY_TOKEN_TTL: string;
	ACCESS_TOKEN_TTL: string;
	REFRESH_TOKEN_TTL: string;
	GOOGLE_AUDIENCES_JSON: string;
	APPLE_AUDIENCES_JSON: string;
	PUBLIC_API_URL: string;
	EMAIL_INTERNAL_TOKEN: string;
	FILES_INTERNAL_TOKEN: string;
	IDENTITY_KEYSET: string;
	INTERNAL_API_TOKEN: string;
	EMAIL_SERVICE: Fetcher;
	FILES_SERVICE: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "D1_EXPECTED_MIGRATION" | "REGISTRATION_MODE" | "APPLICATION_AUDIENCE" | "OPENGROW_IDENTITY_ISSUER" | "OPENGROW_IDENTITY_AUDIENCE" | "OPENGROW_IDENTITY_TOKEN_TTL" | "ACCESS_TOKEN_TTL" | "REFRESH_TOKEN_TTL" | "GOOGLE_AUDIENCES_JSON" | "APPLE_AUDIENCES_JSON" | "PUBLIC_API_URL" | "EMAIL_INTERNAL_TOKEN" | "FILES_INTERNAL_TOKEN" | "IDENTITY_KEYSET" | "INTERNAL_API_TOKEN">> {}
}

// Secret bindings are generated from the declarative service or target registry.
declare namespace Cloudflare {
	interface Env {
	IDENTITY_KEYSET: string;
	EMAIL_INTERNAL_TOKEN: string;
	FILES_INTERNAL_TOKEN: string;
	INTERNAL_API_TOKEN: string;
	INTERNAL_API_TOKEN_PREVIOUS?: string;
	}
}
interface Env {
	IDENTITY_KEYSET: string;
	EMAIL_INTERNAL_TOKEN: string;
	FILES_INTERNAL_TOKEN: string;
	INTERNAL_API_TOKEN: string;
	INTERNAL_API_TOKEN_PREVIOUS?: string;
}
