/* eslint-disable */
// Generated by scripts/cloudflare-types.mjs. Target values are intentionally widened.
interface __BaseEnv_Env {
	DB: D1Database;
	SUPERBOARD_TARGET: string;
	OPENGROW_TARGET: string;
	ENVIRONMENT: string;
	GATEWAY_URL: string;
	FILES_INPUT_ORIGIN: string;
	FILES_INPUT_MAX_BYTES: string;
	OUTPUT_FILE_ORIGIN: string;
	R2_ENDPOINT_URL: string;
	R2_BUCKET_NAME: string;
	STANDARD_MAX_INSTANCES: string;
	PREMIUM_MAX_INSTANCES: string;
	WATERMARK_URL: string;
	DISPATCH_LEASE_MS: string;
	MODAL_ATS_URL: string;
	MODAL_TTS_URL: string;
	R2_READY_MAX_ATTEMPTS: string;
	GATEWAY_INTERNAL_TOKEN: string;
	MODAL_API_KEY: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	STANDARD: DurableObjectNamespace<import("./src/index").Standard>;
	PREMIUM: DurableObjectNamespace<import("./src/index").Premium>;
	DISPATCHER: DurableObjectNamespace<import("./src/index").Dispatcher>;
	MEDIA_WORKFLOW: Workflow<Parameters<import("./src/index").MediaProcessingWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Dispatcher" | "Standard" | "Premium";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPERBOARD_TARGET" | "OPENGROW_TARGET" | "ENVIRONMENT" | "GATEWAY_URL" | "FILES_INPUT_ORIGIN" | "FILES_INPUT_MAX_BYTES" | "OUTPUT_FILE_ORIGIN" | "R2_ENDPOINT_URL" | "R2_BUCKET_NAME" | "STANDARD_MAX_INSTANCES" | "PREMIUM_MAX_INSTANCES" | "WATERMARK_URL" | "DISPATCH_LEASE_MS" | "MODAL_ATS_URL" | "MODAL_TTS_URL" | "R2_READY_MAX_ATTEMPTS" | "GATEWAY_INTERNAL_TOKEN" | "MODAL_API_KEY" | "R2_ACCESS_KEY_ID" | "R2_SECRET_ACCESS_KEY">> {}
}

// Secret bindings are generated from the declarative service or target registry.
declare namespace Cloudflare {
	interface Env {
	MODAL_API_KEY: string;
	GATEWAY_INTERNAL_TOKEN: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	}
}
interface Env {
	MODAL_API_KEY: string;
	GATEWAY_INTERNAL_TOKEN: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
}
