CREATE TABLE IF NOT EXISTS products_billing_ledger_authority (
 project_id TEXT PRIMARY KEY,
 status TEXT NOT NULL CHECK(status IN ('pending','active')),
 changed_at TEXT NOT NULL
);
CREATE TRIGGER IF NOT EXISTS products_billing_products_insert BEFORE INSERT ON products WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = NEW.project_id AND status = 'pending') BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_products_update BEFORE UPDATE ON products WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = OLD.project_id AND status = 'pending') BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_products_delete BEFORE DELETE ON products WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = OLD.project_id AND status = 'pending') BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_financial_customers_insert BEFORE INSERT ON financial_customers WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = NEW.project_id) BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_financial_customers_update BEFORE UPDATE ON financial_customers WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = OLD.project_id) BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_financial_customers_delete BEFORE DELETE ON financial_customers WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = OLD.project_id) BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_entitlements_insert BEFORE INSERT ON entitlements WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = NEW.project_id AND status = 'pending') BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_entitlements_update BEFORE UPDATE ON entitlements WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = OLD.project_id AND status = 'pending') BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_entitlements_delete BEFORE DELETE ON entitlements WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = OLD.project_id AND status = 'pending') BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_entitlement_products_insert BEFORE INSERT ON entitlement_products WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = (SELECT project_id FROM products WHERE id = NEW.product_id) AND status = 'pending') BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_entitlement_products_update BEFORE UPDATE ON entitlement_products WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = (SELECT project_id FROM products WHERE id = OLD.product_id) AND status = 'pending') BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_entitlement_products_delete BEFORE DELETE ON entitlement_products WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = (SELECT project_id FROM products WHERE id = OLD.product_id) AND status = 'pending') BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_purchases_insert BEFORE INSERT ON purchases WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = NEW.project_id) BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_purchases_update BEFORE UPDATE ON purchases WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = OLD.project_id) BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_purchases_delete BEFORE DELETE ON purchases WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = OLD.project_id) BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_purchase_entitlements_insert BEFORE INSERT ON purchase_entitlements WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = (SELECT project_id FROM purchases WHERE id = NEW.purchase_id)) BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_purchase_entitlements_update BEFORE UPDATE ON purchase_entitlements WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = (SELECT project_id FROM purchases WHERE id = OLD.purchase_id)) BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_purchase_entitlements_delete BEFORE DELETE ON purchase_entitlements WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = (SELECT project_id FROM purchases WHERE id = OLD.purchase_id)) BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_subscriptions_insert BEFORE INSERT ON subscriptions WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = NEW.project_id) BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_subscriptions_update BEFORE UPDATE ON subscriptions WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = OLD.project_id) BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_subscriptions_delete BEFORE DELETE ON subscriptions WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = OLD.project_id) BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_refunds_insert BEFORE INSERT ON refunds WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = NEW.project_id) BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_refunds_update BEFORE UPDATE ON refunds WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = OLD.project_id) BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_refunds_delete BEFORE DELETE ON refunds WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = OLD.project_id) BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_audit_events_insert BEFORE INSERT ON audit_events WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = NEW.project_id AND status = 'pending') BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_audit_events_update BEFORE UPDATE ON audit_events WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = OLD.project_id AND status = 'pending') BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_audit_events_delete BEFORE DELETE ON audit_events WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = OLD.project_id AND status = 'pending') BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_idempotency_keys_insert BEFORE INSERT ON idempotency_keys WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = NEW.project_id AND status = 'pending') BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_idempotency_keys_update BEFORE UPDATE ON idempotency_keys WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = OLD.project_id AND status = 'pending') BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
CREATE TRIGGER IF NOT EXISTS products_billing_idempotency_keys_delete BEFORE DELETE ON idempotency_keys WHEN EXISTS (SELECT 1 FROM products_billing_ledger_authority WHERE project_id = OLD.project_id AND status = 'pending') BEGIN SELECT RAISE(ABORT, 'Billing ledger authority is transferred'); END;
