import { spawnSync } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve } from "node:path";

import { parseArgs, root, targetSelectionFromArgs } from "./target.mjs";

const args = parseArgs();
const { targetName, environment } = await targetSelectionFromArgs(args, process.env, {
	allowReference: true,
});
const config = resolve(root, `infra/generated/${targetName}-api-${environment}.jsonc`);

const configResult = spawnSync(
	process.execPath,
	[
		resolve(root, "scripts/cloudflare/config.mjs"),
		"--service",
		"api",
		"--target",
		targetName,
		"--environment",
		environment,
		...(args["allow-unprovisioned"] ? ["--allow-unprovisioned"] : []),
	],
	{ cwd: root, stdio: "inherit", shell: false },
);
if (configResult.status !== 0) process.exit(configResult.status ?? 1);

const temporaryDirectory = await mkdtemp(resolve(tmpdir(), "superboard-api-types-"));
const temporaryTypes = resolve(temporaryDirectory, "generated-env.d.ts");
const output = resolve(root, "packages/plugins/supbrd-core/api/src/generated-env.d.ts");
try {
	const result = spawnSync(
		"npx",
		[
			"wrangler",
			"types",
			temporaryTypes,
			"--env-interface",
			"ApiWorkerGeneratedEnv",
			"--include-runtime=false",
			"--strict-vars=false",
			"--config",
			config,
		],
		{
			cwd: resolve(root, "packages/plugins/supbrd-core/api"),
			encoding: "utf8",
			stdio: ["ignore", "pipe", "inherit"],
		},
	);
	if (result.status !== 0) process.exit(result.status ?? 1);

	const generated = await readFile(temporaryTypes, "utf8");
	const baseInterfaceIndex = generated.indexOf("interface __BaseEnv_ApiWorkerGeneratedEnv");
	const namespaceIndex = generated.indexOf("\ndeclare namespace Cloudflare");
	const publicInterface = generated.match(
		/^interface ApiWorkerGeneratedEnv extends __BaseEnv_ApiWorkerGeneratedEnv \{\}$/m,
	)?.[0];
	if (baseInterfaceIndex < 0 || namespaceIndex < 0 || !publicInterface) {
		throw new Error("Wrangler generated an unexpected environment type format");
	}
	const baseInterface = generated
		.slice(baseInterfaceIndex, namespaceIndex)
		.replace(/\s*\/\*\s+(?!eslint-disable\b)[^*]+\s+\*\//gi, "")
		.trimEnd();
	await writeFile(
		output,
		[
			"/* eslint-disable */",
			"// Generated by scripts/cloudflare/api-types.mjs. Do not edit manually.",
			baseInterface,
			`export ${publicInterface}`,
			"",
		].join("\n"),
		{ mode: 0o600 },
	);
	console.log("packages/plugins/supbrd-core/api/src/generated-env.d.ts");
} finally {
	await rm(temporaryDirectory, { recursive: true, force: true });
}
