import { readFile, rm, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";
import {
  loadTarget,
  parseArgs,
  root,
  targetSelectionFromArgs,
} from "./cloudflare-target.mjs";
import {
  DOMAIN_SERVICES,
  DOMAIN_SERVICE_REGISTRY,
  PLATFORM_SERVICE_SECRETS,
  assertServiceForTarget,
  isOptionalSecretBinding,
  managedWorkerDefinition,
} from "./cloudflare-services.mjs";

const args = parseArgs();
const service = args.service;
const { targetName, environment } = await targetSelectionFromArgs(
  args,
  process.env,
  { allowReference: true },
);
const { target } = await loadTarget(targetName);
assertServiceForTarget(target, service);
const managedWorker = managedWorkerDefinition(target, service);
if (
  !managedWorker &&
  ![
    ...DOMAIN_SERVICES,
    "site",
    "billing",
    "messaging",
    "email",
    "identity",
    "files",
    "observability",
    "mcp",
    "custom",
  ].includes(service)
) {
  throw new Error("cloudflare-types does not generate API or Dashboard types");
}
if (service === "custom" && !target.customWorker) {
  throw new Error(`${targetName} does not declare a custom Worker`);
}

run(process.execPath, [
  resolve(root, "scripts", "cloudflare-config.mjs"),
  "--service",
  service,
  "--target",
  targetName,
  "--environment",
  environment,
  ...(args["allow-disabled"] ? ["--allow-disabled"] : []),
  ...(args["allow-unprovisioned"] ? ["--allow-unprovisioned"] : []),
]);

const workerDirectory = managedWorker
  ? resolve(root, managedWorker.packagePath)
  : service === "custom"
    ? resolve(root, target.customWorker.packagePath)
    : service === "site"
      ? resolve(root, "apps", "site")
      : resolve(root, "workers", service);
const outputPath = resolve(workerDirectory, "worker-configuration.d.ts");
const configPath = resolve(
  root,
  "deploy",
  "generated",
  `${targetName}-${service}-${environment}.jsonc`,
);
const generatedPath = resolve(
  workerDirectory,
  ".worker-configuration.generated.d.ts",
);
try {
  run(
    "npx",
    [
      "wrangler",
      "types",
      generatedPath,
      "--config",
      configPath,
      "--include-runtime",
      service === "site" ? "true" : "false",
      "--strict-vars=false",
    ],
    workerDirectory,
  );

  const declaredSecrets = managedWorker
    ? managedWorker.secrets
    : service === "custom"
      ? [...target.customWorker.secrets, "CUSTOM_WORKER_TOKEN_PREVIOUS"]
      : DOMAIN_SERVICES.includes(service)
        ? DOMAIN_SERVICE_REGISTRY[service].secrets
        : PLATFORM_SERVICE_SECRETS[service];
  const optionalSecrets = new Set([
    ...declaredSecrets.filter(isOptionalSecretBinding),
    ...(service === "site" ? ["SUPERBOARD_RELEASE_PRIVATE_JWK"] : []),
    ...(service === "email"
      ? [
          "MAIL_PREVIEW_TOKEN",
          "AWS_SES_SMTP_USERNAME",
          "AWS_SES_SMTP_PASSWORD",
          "AWS_SES_SNS_TOPIC_ARN",
          "SMTP_HOST",
          "SMTP_PORT",
          "SMTP_SECURITY",
          "SMTP_USERNAME",
          "SMTP_PASSWORD",
        ]
      : []),
  ]);
  const secretFields = declaredSecrets
    .map((secret) => {
      const optional = optionalSecrets.has(secret) ? "?" : "";
      const type =
        service === "email" && secret === "SMTP_SECURITY"
          ? '"tls" | "starttls" | "plain"'
          : "string";
      return `\t${secret}${optional}: ${type};`;
    })
    .join("\n");
  let generated = (await readFile(generatedPath, "utf8"))
    .replaceAll(
      configPath,
      `deploy/generated/${targetName}-${service}-${environment}.jsonc`,
    )
    .replaceAll(generatedPath, "worker-configuration.d.ts")
    .replace(
      /^\/\/ Generated by Wrangler[^\n]*$/m,
      "// Generated by scripts/cloudflare-types.mjs. Target values are intentionally widened.",
    )
    .replace(/\s*\/\*\s+(?!eslint-disable\b)[^*]+\s+\*\//gi, "");
  if (service === "email") {
    generated = [
      'type EmailQueueJob = { type: "email.deliver"; messageId: string };',
      generated
        .replace(
          "\tEMAIL_QUEUE: Queue;",
          "\tEMAIL_QUEUE: Queue<EmailQueueJob>;",
        )
        .replace(
          "\tMAIL_TRANSPORT: string;",
          '\tMAIL_TRANSPORT: "capture" | "smtp";',
        )
        .replace(
          "\tMAIL_PROVIDER: string;",
          '\tMAIL_PROVIDER: "smtp" | "aws-ses";',
        ),
    ].join("\n");
  }
  await writeFile(
    outputPath,
    `${generated.trimEnd()}\n${[
      "",
      "// Secret bindings are generated from the declarative service or target registry.",
      "declare namespace Cloudflare {",
      "\tinterface Env {",
      secretFields,
      "\t}",
      "}",
      "interface Env {",
      secretFields,
      "}",
      "",
    ].join("\n")}`,
  );
} finally {
  await rm(generatedPath, { force: true });
}

function run(command, commandArgs, cwd = root) {
  const result = spawnSync(command, commandArgs, {
    cwd,
    stdio: "inherit",
    shell: false,
  });
  if (result.status !== 0) process.exit(result.status ?? 1);
}
