/* eslint-disable */
// Generated by scripts/cloudflare/types.mjs. Target values are intentionally widened.
interface __BaseEnv_Env {
	ENVIRONMENT: string;
	SUPERBOARD_TARGET: string;
	MCP_DOMAIN: string;
	MCP_LEGACY_ORIGINS_JSON: string;
	PUBLIC_API_URL: string;
	PUBLIC_MCP_URL: string;
	SUPERBOARD_INSTANCE_ID: string;
	SUPERBOARD_PLUGIN_LIFECYCLE: string;
	API_SERVICE: Fetcher;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "SUPERBOARD_TARGET" | "MCP_DOMAIN" | "MCP_LEGACY_ORIGINS_JSON" | "PUBLIC_API_URL" | "PUBLIC_MCP_URL" | "SUPERBOARD_INSTANCE_ID" | "SUPERBOARD_PLUGIN_LIFECYCLE">> {}
}

// Secret bindings are generated from the declarative service or target registry.
declare namespace Cloudflare {
	interface Env {

	}
}
interface Env {

}
