"use client";

import type { SortType } from "@/types";
import { Button } from "@/components/ui/button";
import { parseSecondsInDaysHoursMinutesSeconds } from "@/lib/utils";
import { AccessorKeyColumnDef } from "@tanstack/react-table";
import { formatSlashDate } from "@/lib/dateUtils";
import { checkSortDirection } from "../dynamic_links/links/LinksTableColumns";
import { Badge } from "../ui/badge";
import { numberFormatter } from "../../utils/numberFormatter";
import { Tooltip, TooltipContent, TooltipTrigger } from "../ui/tooltip";
import { formatPlatformName } from "@/lib/utils";
import { formatCountry } from "@/lib/country";

const renderToolTipContent = (key: string) => {
  let text = "";

  switch (key) {
    case "Opens":
      text = "This represents the number of times your app was opened";
      break;
    case "Views":
      text = "The number of links the user opened in a web browser.";
      break;
    case "Installs":
      text =
        "This represents the number of times your app was installed on the device. This can be 0 or 1. If 0, the customer did not install your app.";
      break;
    case "Reinstalls":
      text =
        "The number of app reinstalls generated by the link. A reinstall occurs when the app is deleted and reinstalled on the same device.";
      break;
    case "Reactivations":
      text =
        "The number of users who reopened the app after not using it for more than 7 days.";
      break;
    case "Platform":
      text = "The platform of the user's device";
      break;
    case "Invited users":
      text =
        "The total number of users who installed your app after being invited by the customer.";
      break;
    case "Time spent":
      text = "Time spent in the app.";
      break;

    default:
      break;
  }

  return (
    <TooltipContent>
      <p>{text}</p>
    </TooltipContent>
  );
};

export const getVisitorsTableColumns = (
  sort: SortType,
  setSort: React.Dispatch<React.SetStateAction<SortType>>
): AccessorKeyColumnDef<VisitorMetrics>[] => [
  {
    accessorKey: "uuid",
    header: () => <Button variant="ghost">Id</Button>,
    cell: ({ row }) => {
      return (
        <div>
          <p>
            {" "}
            {row.original.uuid.slice(0, 8) +
              "..." +
              row.original.uuid.slice(-6) || "-"}
          </p>
        </div>
      );
    },
  },
  {
    accessorKey: "sdk_identifier",
    header: () => <Button variant="ghost">SDK Identifier</Button>,

    cell: ({ row }) => {
      return (
        <div>
          <p className="truncate overflow-hidden text-ellipsis">
            {row.original.sdk_identifier || "-"}
          </p>
        </div>
      );
    },
  },
  {
    accessorKey: "platform",
    header: () => (
      <Tooltip>
        <TooltipTrigger asChild>
          <Button variant="ghost">Platform</Button>
        </TooltipTrigger>
        {renderToolTipContent("Platform")}
      </Tooltip>
    ),
    cell: ({ row }) => {
      return (
        <div>
          <Badge variant={"outline"} className="border-sidebar-border">
            {formatPlatformName(row.original.platform)}
          </Badge>
        </div>
      );
    },
  },
  {
    accessorKey: "country",
    header: () => <Button variant="ghost">Pays</Button>,
    cell: ({ row }) => <div>{formatCountry(row.original.country_code)}</div>,
  },
  {
    accessorKey: "views",
    header: () => renderSortableHeader("Views", "views", setSort, sort, true),

    cell: ({ row }) => {
      return (
        <div>
          <p>
            {row.original.total_views
              ? numberFormatter.format(row.original.total_views)
              : "-"}
          </p>
        </div>
      );
    },
  },
  {
    accessorKey: "opens",
    header: () =>
      renderSortableHeader("Opens", "app_opens", setSort, sort, true),
    cell: ({ row }) => {
      return (
        <div>
          <p>
            {row.original.total_opens
              ? numberFormatter.format(row.original.total_opens)
              : "-"}
          </p>
        </div>
      );
    },
  },
  {
    accessorKey: "installs",
    header: () =>
      renderSortableHeader("Installs", "installs", setSort, sort, true),
    cell: ({ row }) => {
      return (
        <div>
          <p>
            {row.original.total_installs
              ? numberFormatter.format(row.original.total_installs)
              : "-"}
          </p>
        </div>
      );
    },
  },
  {
    accessorKey: "reinstalls",
    header: () =>
      renderSortableHeader("Reinstalls", "reinstalls", setSort, sort, true),
    cell: ({ row }) => {
      return (
        <div>
          <p>
            {row.original.total_reinstalls
              ? numberFormatter.format(row.original.total_reinstalls)
              : "-"}
          </p>
        </div>
      );
    },
  },
  {
    accessorKey: "reactivations",
    header: () =>
      renderSortableHeader(
        "Reactivations",
        "reactivations",
        setSort,
        sort,
        true
      ),
    cell: ({ row }) => {
      return (
        <div>
          <p>
            {row.original.total_reactivations
              ? numberFormatter.format(row.original.total_reactivations)
              : "-"}
          </p>
        </div>
      );
    },
  },
  {
    accessorKey: "invited_users",
    header: () =>
      renderSortableHeader(
        "Invited users",
        "user_referred",
        setSort,
        sort,
        true
      ),
    cell: ({ row }) => {
      return (
        <div>
          <p>
            {row.original.total_user_referred
              ? numberFormatter.format(row.original.total_user_referred)
              : "-"}
          </p>
        </div>
      );
    },
  },
  {
    accessorKey: "time_spent",
    header: () =>
      renderSortableHeader("Time spent", "time_spent", setSort, sort, true),
    cell: ({ row }) => {
      return (
        <div>
          <p>
            {parseSecondsInDaysHoursMinutesSeconds(
              row.original.total_time_spent
            ) || "-"}
          </p>
        </div>
      );
    },
  },
  {
    accessorKey: "date",
    header: () => renderSortableHeader("Date", "updated_at", setSort, sort),
    cell: ({ row }) => {
      return (
        <div>
          <p>{formatSlashDate(row.original.updated_at)}</p>
        </div>
      );
    },
  },
];

export interface VisitorMetrics {
  id: string;
  uuid: string;
  updated_at: string;
  total_views: number;
  total_opens: number;
  total_installs: number;
  total_reinstalls: number;
  sdk_identifier: string;
  invited_by?: string;
  total_user_referred: number;
  platform: string;
  country_code?: string | null;
  total_reactivations: number;
  total_time_spent: number;
}

export const renderSortableHeader = (
  label: string,
  sortKey: string,
  setSort: React.Dispatch<React.SetStateAction<SortType>>,
  sort: SortType,
  tooltip?: boolean
) => (
  <Tooltip>
    <TooltipTrigger asChild>
      <Button
        variant="ghost"
        onClick={() =>
          setSort((prev) => ({
            sortKey,
            ascending: prev.sortKey === sortKey ? !prev.ascending : true,
          }))
        }
      >
        {label}
        {checkSortDirection(sortKey, sort)}
        {tooltip && renderToolTipContent(label)}
      </Button>
    </TooltipTrigger>
  </Tooltip>
);
