ENV['RCT_NEW_ARCH_ENABLED'] = '1'
source 'https://github.com/CocoaPods/Specs.git'
require 'json'

native_contract = JSON.parse(
  File.read(File.expand_path('../../plugin/native-contract.json', __dir__))
)

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'OpenGrowWrapperExample' do
  # The native iOS SDK is not published to CocoaPods Trunk. Resolve the
  # reviewed podspec whose own source is the immutable SDK Git tag.
  pod native_contract["ios"]["packageName"], :podspec => native_contract["ios"]["podspecUrl"]
  config = use_native_modules!
  
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  pre_install do |installer|
    system("cd ../../ && npx bob build --target codegen")
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
