/* eslint-disable */
// Generated by scripts/cloudflare-types.mjs. Target values are intentionally widened.
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	MARKETING_QUEUE: Queue;
	ENVIRONMENT: string;
	SERVICE_NAME: string;
	D1_EXPECTED_MIGRATION: string;
	AUTH_GATEWAY_ISSUER: string;
	AUTH_GATEWAY_AUDIENCE: string;
	AUTH_GATEWAY_JWKS_URL: string;
	PUBLIC_API_URL: string;
	QUEUE_NAME: string;
	DLQ_NAME: string;
	ANALYTICS_ID_HASH_KEY: string;
	EMAIL_INTERNAL_TOKEN: string;
	INTERNAL_API_TOKEN: string;
	SMTP_ENCRYPTION_KEY: string;
	TRACKING_SIGNING_KEY: string;
	EMAIL_SERVICE: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "SERVICE_NAME" | "D1_EXPECTED_MIGRATION" | "AUTH_GATEWAY_ISSUER" | "AUTH_GATEWAY_AUDIENCE" | "AUTH_GATEWAY_JWKS_URL" | "PUBLIC_API_URL" | "QUEUE_NAME" | "DLQ_NAME" | "ANALYTICS_ID_HASH_KEY" | "EMAIL_INTERNAL_TOKEN" | "INTERNAL_API_TOKEN" | "SMTP_ENCRYPTION_KEY" | "TRACKING_SIGNING_KEY">> {}
}

// Secret bindings are generated from the declarative service or target registry.
declare namespace Cloudflare {
	interface Env {
	INTERNAL_API_TOKEN: string;
	INTERNAL_API_TOKEN_PREVIOUS?: string;
	EMAIL_INTERNAL_TOKEN: string;
	ANALYTICS_ID_HASH_KEY: string;
	ANALYTICS_ID_HASH_KEY_PREVIOUS?: string;
	SMTP_ENCRYPTION_KEY: string;
	TRACKING_SIGNING_KEY: string;
	}
}
interface Env {
	INTERNAL_API_TOKEN: string;
	INTERNAL_API_TOKEN_PREVIOUS?: string;
	EMAIL_INTERNAL_TOKEN: string;
	ANALYTICS_ID_HASH_KEY: string;
	ANALYTICS_ID_HASH_KEY_PREVIOUS?: string;
	SMTP_ENCRYPTION_KEY: string;
	TRACKING_SIGNING_KEY: string;
}
