/* eslint-disable */
// Generated by scripts/cloudflare-types.mjs. Target values are intentionally widened.
interface __BaseEnv_Env {
	REFERENCE_DB: D1Database;
	APP_KEY: string;
	ENVIRONMENT: string;
	CUSTOM_WORKER_CAPABILITIES: string;
	D1_EXPECTED_MIGRATION: string;
	REFERENCE_JOB_RETENTION_DAYS: string;
	CUSTOM_WORKER_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_KEY" | "ENVIRONMENT" | "CUSTOM_WORKER_CAPABILITIES" | "D1_EXPECTED_MIGRATION" | "REFERENCE_JOB_RETENTION_DAYS" | "CUSTOM_WORKER_TOKEN">> {}
}

// Secret bindings are generated from the declarative service or target registry.
declare namespace Cloudflare {
	interface Env {
	CUSTOM_WORKER_TOKEN: string;
	CUSTOM_WORKER_TOKEN_PREVIOUS?: string;
	}
}
interface Env {
	CUSTOM_WORKER_TOKEN: string;
	CUSTOM_WORKER_TOKEN_PREVIOUS?: string;
}
